name: Run Step Change

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,12 * * *'

jobs:
  ChangBuShu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: pip install dependencies
      run: pip install -r ./requirements.txt

    - name: change steps
      run: python changebushu_action.py
      env:
        USER_PHONE: ${{ secrets.USER_PHONE }}
        USER_PWD: ${{ secrets.USER_PWD }}
        STEP: ${{ secrets.STEP }}
        STEP_MIN: ${{ secrets.STEP_MIN }}
        STEP_MAX: ${{ secrets.STEP_MAX }}
